### ISSUE TITLE
Serial port settings for RaspBee..

### ISSUE THREAD

**Issue by pwielders** [dresden-elektronik/deconz-serial-protocol#14]
I currently have a C++ implementation of the SerialProtocol implemented for Windows/Linux and it is working fine with the ConBee (Serial over USB). Now I wanted to switch to the Raspbee (Serial on the RASPBERRYPi) but looks like it is not reporting in. I assume the protocols are the same. 
I can not clearly find the parameters that I need to use. Assumption is 38400, No parity, 8 databits, 1 stopbit. Serial terminal programmed as raw.

Is this correct?

**Comment by Adminiuga** [comment]
It is exactly the same settings. 38400 no flow control. 
But make sure your serial port is enabled on GPIO pins. Make sure deCONZ runs with it.

**Comment by pwielders** [comment]
All working but will raise a new issue ;-) Thansk for the support sofar.
