### ISSUE TITLE
Native serial UART protocol support for RaspBee and ConBee in Home Assistant without deCONZ software

### ISSUE THREAD

**Issue by Gamester17** [dresden-elektronik/deconz-serial-protocol#2]
Dresden-Elektronik should consider adding native serial protocol (UART) support for ConBee and  RaspBee hardware to open source home automation software such as Home Assistant and its Hass.io (Home Assistant appliance OS for RAspberry Pi). 

That is, make open source home automation software such as Home Assistant support using ConBee and RaspBee adapters directly via serial potocol over UART and CLI using existing open source Zigbee libraries without the need to the deCONZ gateway software. 

Commercial motivation for Dresden-Elektronik; open source home automation software such as Home Assistant and Hass.io (Home Assistant embedded Linux OS for Raspberry Pi) are the very popular today and as they are already available and used by perhaps millions of people right now, Dresden-Elektronik would most likely sell many more devices if its RaspBee and ConBee hardware had native support them inside open source home automation software such as Home Assistant and Hass.io

Please checkout: https://home-assistant.io

as well as

https://home-assistant.io/hassio/

Home Assistant recently gained native serial protocol (UART) support for ZigBee Home Automation via the ZigPy (Zigbee for Python) open source library that currently can only communicate with XBee and EmberZNet based devices (competing USB adapter by Silicon Labs) via other Python modules which in turn communicates with different radios native serial protocol (UART) for zigpy, for more information see:

https://github.com/zigpy/zigpy

https://github.com/zigpy/bellows
https://github.com/zigpy/zigpy-xbee
https://github.com/doudz/zigpy-zigate

Update! @damarco and @Equidamoid have both independently started working on zigpy radio libraries a native serial UART protocol for Conbee/Raspbee here:

https://github.com/zigpy/zigpy-deconz

https://github.com/Equidamoid/pyconz/

See also:

https://home-assistant.io/components/zha/

https://github.com/home-assistant/home-assistant/tree/dev/homeassistant/components/zha

https://github.com/home-assistant/home-assistant/pull/6263

https://github.com/home-assistant/home-assistant/pull/12187
 
https://github.com/home-assistant/home-assistant/pull/19664

https://github.com/home-assistant/home-assistant-polymer/pull/2389

https://github.com/home-assistant/home-assistant-polymer/pull/2421

**Comment by Adminiuga** [comment]
Question: Does ConBee keeps its children in the neighbour table after the ConBee is power cycled?

I'm troubleshooting an issue with [HA ZHA integration](https://github.com/home-assistant/core/issues/36824#issuecomment-647453445), where the child device of ConBee is not reachable after a power cycle (Just a ConBee and two child devices), however we do get the attribute reports from the device. Just cannot send anything to the device and all tx attempts fail with `MAC_NO_ACK/0xE9` status.

Querrying  ConBee's neighbour table shows an empty table:
```
2020-06-22 22:32:00 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x174b002b0024002602000000040000e61ee50f006f0d00000000318005006e0000000000aff90000020200
2020-06-22 22:32:00 DEBUG (MainThread) [zigpy_deconz.api] APS data indication response: [36, <DeviceState.APSDE_DATA_REQUEST_SLOTS_AVAILABLE|APSDE_DATA_CONFIRM|2: 38>, <DeconzAddress address_mode=ADDRESS_MODE.NWK address=0x0000>, 0, <DeconzAddress address_mode=ADDRESS_MODE.NWK_AND_IEEE address=0x0000>, 0, 0, 32817, b'n\x00\x00\x00\x00', 0, 175, 249, 0, 0, 2, 2, 0]
2020-06-22 22:32:00 DEBUG (MainThread) [zigpy_deconz.api] 'aps_data_indication' response from <DeconzAddress address_mode=ADDRESS_MODE.NWK_AND_IEEE address=0x0000>, ep: 0, profile: 0x0000, cluster_id: 0x8031, data: b'6e00000000'
2020-06-22 22:32:00 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_confirm (0,)
2020-06-22 22:32:00 DEBUG (MainThread) [zigpy_deconz.uart] Send: 0x044c0007000000
2020-06-22 22:32:00 DEBUG (MainThread) [zigpy_deconz.uart] Frame received: 0x044c0013000c00226f02000000000000000000
2020-06-22 22:32:00 DEBUG (MainThread) [zigpy_deconz.api] APS data confirm response for request with id 111: 00
2020-06-22 22:32:00 DEBUG (MainThread) [zigpy_deconz.api] Request id: 0x6f 'aps_data_confirm' for <DeconzAddressEndpoint address_mode=ADDRESS_MODE.NWK address=0x0000 endpoint=0>, status: 0x00
2020-06-22 22:32:00 DEBUG (MainThread) [custom_components.zha_map.neighbour] [00:0d:6f:00:0f:e5:1e:e6]: neighbor request Status: Status.SUCCESS. Response: <Optional Entries=0 StartIndex=0 NeighborTableList=[]>
2020-06-22 22:32:00 DEBUG (MainThread) [custom_components.zha_map.neighbour] [00:0d:6f:00:0f:e5:1e:e6]: Done scanning. Total 0 neighbours
```

, but if you power cycle the child and ConBee gets a ZDO device annce, then the child is shown in the neighbour table.

Now, if i just start deconz, then it finds its child and after that it is also in the ConBee's neighbour table. I've tried to check deConz log, but other than 
```
17:24:56:112 void zmMaster::sendNextCommand() seq: 66, CMD_APS_DATA_INDICATION2
17:24:56:112 zmMaster::setState() state: I -> B
17:24:56:141 RX: 1742002D0026002A020000010475F95DD14403006F0D0001040101020700081D0A1E00300075F9FFA3000102D517:24:56:141 SerialCom::onPacket cmd: 0x17, seq: 0x66
17:24:56:141 void zmMaster::processPacked(zm_command*) seq: 66, CMD_APS_DATA_INDICATION2
17:24:56:141 void zmMaster::checkStatus0(uint8_t*) conf: 0, free-slots: 1, ind: 1, apsQueue: 1
17:24:56:142 APS-DATA.indication srcAddr: 0xf975, srcEp: 0x01 dstAddrMode: 2, profile: 0x0104, cluster: 0x0201, lqi: 255, rssi: -43
17:24:56:142    asdu: 081d0a1e003000
17:24:56:142 APS-DATA.indication from child 0xF975
17:24:56:143 Master: verify child node: 0x000D6F000344D15D
17:24:56:143 verify 0x000d6f000344d15d is child node after 0 s
17:24:56:143 Node data 0x000d6f000344d15d profileId: 0x0104, clusterId: 0x0201
17:24:56:144 ZCL attribute report 0x000D6F000344D15D for cluster: 0x0201, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
17:24:56:145    payload: 1e003000
```

I couldn't find anything. I always was under the impression, that Zigbee routers and coordinators always keep the list of their children even after a cold start. This is not what I'm seeing with `zigpy-deconz`, but deCONZ itself doesn't have this problem. So what is the trick to communicate with ConBee's child devices after a power cycle?

**Comment by Adminiuga** [comment]
deCONZ seem to be using an undocumented command, in logs shows as

18:43:38:301 zmMaster::setState() state: B -> I
18:43:38:301 void zmMaster::sendNextCommand() seq: 71, CMD_UNKNOWN
18:43:38:301 zmMaster::setState() state: I -> B
18:43:38:328 RX: 1D470013000C000175F95DD14403006F0D008018:43:38:328 SerialCom::onPacket cmd: 0x1D, seq: 0x71
18:43:38:329 void zmMaster::processPacked(zm_command*) seq: 71, CMD_UNKNOWN
18:43:38:330 verify neighbor status: APP_SUCCESS (0x00) 
18:43:38:330 zmMaster::setState() state: B -> I
Which corresponds to

write(18, "\xc0\x1d\x47\x00\x13\x00\x0c\x00\x01\x75\xf9\x5d\xd1\x44\x03\x00\x6f\x0d\x00\x80\x9d\xfb\xc0", 23) = 23
read(18, "\xc0\x1d\x47\x00\x13\x00\x0c\x00\x01\x75\xf9\x5d\xd1\x44\x03\x00\x6f\x0d\x00\x80\x9d\xfb\xc0", 32768) = 23
looks like a standard frame header + payload. Payload 12 bytes long appears to be:
uint8_t -- Unknown, neighbor index or is it device index key from the DB?
uint16_t -- NWK address of the neighbour
uint64_t -- EUI64 address
uint8_t -- Unknown

**Comment by manup** [comment]
The child table usually gets filled again after incoming commands with a valid network key, but I've just checked the code indeed there is a command to modify the neighbor table for sleeping end-devices. Damn totally missed this, I'll update the docs later on. Meanwhile here is a screenshot of the implementation in deCONZ. 

![image](https://user-images.githubusercontent.com/383386/85835213-ee57dd80-b794-11ea-87e9-cb407466c984.png)

Likely the update neighbor command (0x1D) is needed then children are just polling via MAC data requests which aren't encrypted and don't hold the MAC address and therefore the device can't be safely assumed to be part of the network.

> Do I need to keep track of all children (and neighbours) and store this info outside of ConBee and restore those on startup? or is there a trick for  ConBee to remember its children at least?

In case of deCONZ all devices which are joined are kept in a SQLite database file. I'm afraid for the end-devices  which need above command currently this is needed. Anyway I think this should added to the firmware directly to keep the burden from the application.

**Comment by Adminiuga** [comment]
> The child table usually gets filled again after incoming commands with a valid network key

Then it might be a bug, as it's not happening by ConBee itself. I've reproduced on ConBee I (latest firmware from May) based on a report for a ConBee II (same behavior on the latest two firmwares) 
They're incoming request - attribute reports from the sleepy end device, received normally, but neighbour table still empty after 12 hours.
In my case I reproduced with a Centralite Thermostat, in original issue it was a Yale lock.

**Comment by Adminiuga** [comment]
quick question: `DECONZ_PROTOCOL_VERSION_1_7` is `0x0107` ?

**Comment by Adminiuga** [comment]
>In case of deCONZ all devices which are joined are kept in a SQLite database file. I'm afraid for the end-devices which need above command currently this is needed.

another quick question: you keep the database of the joined devices, but in `zll.db` there's no information about the "parent" device is there? in other words: is it safe to issue the `0x1D` command just for any sleepy end device when we're trying to communicate with it for the very 1st time after the powercycle? Or do I have to issue `0x1D` only for sleepy end devices joined directly to ConBee only -- implying that I need to keep a table of ConBee neighbours

> Anyway I think this should added to the firmware directly to keep the burden from the application.

That would be awesome 👍

**Comment by Hedda** [comment]
@manup and @ChrisHae Can I suggest that you at dresden-elektronik try to reach out to @pipiche38 (Patrick Pichon) about possible donating ConBee/RaspBee hardware to him so he can test deCONZ hardware with the new Zigbee plugin implementation based on  [zigpy](https://github.com/zigpy/zigpy) that he is developing for Domoticz home automation software? 

https://github.com/pipiche38/Domoticz-Zigpy/

If the project is successful then his plugin will add ConBee/RaspBee plug-and-play hardware to Domoticz without deCONZ gateway.

I know that @dresden-elektronik has made hardware donations of your deCONZ based Zigbee adapters to free and open source projects in the past, including developers working on the [zigpy](https://github.com/zigpy/zigpy) project, so though you might be willing to do same here? After all, zigpy already support ConBee and RaspBee adapters and the more projects that support those should mean more people buying and using your Zigbee adapters.

Please see and maybe also reply in respective suggested posted to pipiche38 here:

https://github.com/pipiche38/Domoticz-Zigpy/issues/5

If you could donate one, two or few of your ConBee and RaspBee adapters (USB dongles or Raspberry Pi Shields) to @pipiche38 then maybe he that can help him with his developing effort as it would give him the possibility to also test the [zigpy-deconz](https://github.com/zigpy/zigpy-deconz) radio library for [zigpy](https://github.com/zigpy/zigpy) to try out their compatibility with ConBee and RaspBee adapters as zigpy can support many different adapters. Your hardware adapters could perhaps later even be used as one of the reference hardware tested for that new zigpy based Domoticz plugin, though no strings attached of course as these are still hobby projects at their core with only one developer so far. 

https://github.com/zigpy/zigpy

https://github.com/zigpy/zigpy-deconz

Please understand that pipiche38 is still in a very early stage of developing his "Domoticz-Zigpy" plugin for [Domoticz](https://www.domoticz.com) (a popular free and open-source home automation software), I understand in fact the project is so a such early in development that is not yet usable to end-users, however, I read on Domoticz community forum that he currently only has access to ZiGate Zigbee adapters (this as pipiche38 is also the developer of an already existing ZiGate plugin for Domoticz). So at least we know that pipiche38 already has the experience and skills to develop Zigbee plugins for Domoticz.

https://github.com/pipiche38/Domoticz-Zigate-Wiki/blob/master/en-eng/Home.md

https://www.domoticz.com/wiki/Zigate

I believe that both zigpy, Domoticz, and this new "Domoticz-Zigpy" plugin are all only spare-time hobby projects at this point, but still, I think that teaming up might give all involved projects some continued positive recognition in the Domoticz community and the whole home automation scene in general which might attract more developers and willing alpha/beta-testers from the community to come to help out with all these involved projects which in the long run could benefit all users wanting Zigbee in Domoticz to become more mature and working with more Zigbee hardware dongles than it is today.

**Comment by manup** [comment]
@Hedda seems to be a good project. Can @pipiche38 send me a small mail to mpi@dresden-elektronik.de with his shipping address and reference to the Domoticz-Zigbpy project, then we'll send him the needed devices.

**Comment by Hedda** [comment]
> @Hedda seems to be a good project. Can @pipiche38 send me a small mail to [mpi@dresden-elektronik.de](mailto:mpi@dresden-elektronik.de) with his shipping address and reference to the Domoticz-Zigbpy project, then we'll send him the needed devices.

That is very nice of you! I also see that @pipiche38 replied in https://github.com/pipiche38/Domoticz-Zigpy/issues/5 that he has now made contact you with.

Hope that the adapter(s) arrives to him without issues and that he has no problems testing it/them with his Domoticz-Zigpy plugin:

https://github.com/pipiche38/Domoticz-Zigpy/

**Comment by wang70880** [comment]
Sorry to bother you guys. I am curious that what customized firmwares we can design on Raspbee? I think the official firmware is limited, e.g., changing PANID, and do you have any idea for the design of customized firmware?

**Comment by Hedda** [comment]
> Sorry to bother you guys. I am curious that what customized firmwares we can design on Raspbee? I think the official firmware is limited, e.g., changing PANID, and do you have any idea for the design of customized firmware?

If you want the deconz serial protocol / API extended then I believe that the current process is to submit feature request as issues:

https://github.com/dresden-elektronik/deconz-serial-protocol/issues

That is, submit separate issue requests for each new feature and/or function that you like to see implemented in their protocols.

Or do you mean writing custom application firmware for the Atmel ATSAMR21B18 microcontroller used inside ConBee / RaspBee?

https://phoscon.de/en/conbee2/techspec
https://phoscon.de/en/raspbee2/techspec

As far as I know, ConBee / RaspBee is a closed platform, meaning their Zigbee stack is not open source and Dresden Electronics don't have a deCONZ firmware SDK that would allow you to build and compile your own firmware based on their proprietary Zigbee coordinator application code, but I guess that you could maybe use flash hardware with custom firmware based on developing software for Atmel or ATSAMR21B18-MZ210PA and/or ATSAMR21ZLL

https://www.microchip.com/developmenttools/ProductDetails/atsamr21zll-ek
https://www.microchip.com/wwwproducts/en/ATSAMR21B18

Regardless I am pretty sure that such a subject is off-topic for this topic so might want to discuss that elsewhere, such as maybe:

https://community.atmel.com/forums/802154zigbee

**Comment by wang70880** [comment]
> > Sorry to bother you guys. I am curious that what customized firmwares we can design on Raspbee? I think the official firmware is limited, e.g., changing PANID, and do you have any idea for the design of customized firmware?
> 
> If you want the deconz serial protocol / API extended then I believe that the current process is to submit feature request as issues:
> 
> https://github.com/dresden-elektronik/deconz-serial-protocol/issues
> 
> That is, submit separate issue requests for each new feature and/or function that you like to see implemented in their protocols.
> 
> Or do you mean writing custom application firmware for the Atmel ATSAMR21B18 microcontroller used inside ConBee / RaspBee?
> 
> https://phoscon.de/en/conbee2/techspec
> https://phoscon.de/en/raspbee2/techspec
> 
> As far as I know, ConBee / RaspBee is a closed platform, meaning their application firmware is not open source and Dresden Electronics don't have a deCONZ firmware SDK that would allow you to build and compile your own firmware based on their proprietary Zigbee coordinator application code, but I guess that you could maybe use flash ConBee or RaspBee as Atmel ATSAMR21B18-MZ210PA and/or ATSAMR21ZLL hardware with your own custom firmware based the BitCloud ZigBee PRO software stack from Atmelon developing using the software.
> 
> https://www.microchip.com/developmenttools/ProductDetails/atsamr21zll-ek
> https://www.microchip.com/wwwproducts/en/ATSAMR21B18
> 
> Regardless I am pretty sure that such a subject is off-topic for this topic so might want to discuss that elsewhere, such as maybe:
> 
> https://community.atmel.com/forums/802154zigbee

Thanks, and I am sorry to choose a wrong place to ask. Let me try your solution, and if there is any further question, I will go to the correct thread.

**Comment by SylvainPer** [comment]
Hello, can I have access to the documentation?
Just received the conbee ii, thanks @manup for the support of Domoticz-zigbee plugin.
