### ISSUE TITLE
Unknown Command ID 0x1F

### ISSUE THREAD

**Issue by dbdbdb** [dresden-elektronik/deconz-serial-protocol#6]
I get a bunch of commands from the conbee stick with Command ID 0x1F that I don't know how to interpret. Anyone know what it is?

There is nothing in the serial protocol pdf about it.

**Comment by Adminiuga** [comment]
0x1F is the simplified beacon command. 
uint16_t: source NWK
uint16_t: pan_id
uint8_t: channel
uint8_t: flags
uint8_t: network update id

**Comment by dbdbdb** [comment]
Thanks a lot. That's all I needed even if I'm curious about the flags.

I kind if forgot to both thank you and to close this case, but now is as good time as any.
